from setuptools import find_packages, setup

setup(
    name="flsd",
    version="0.2.0",
    description="Financial data pipeline and dashboard system for FLSD",
    author="FLSD Data Team",
    packages=find_packages(),
    python_requires=">=3.9",
    install_requires=[
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "plotly>=5.18.0",
        "jupyter>=1.0.0",
        "notebook>=7.0.0",
        "scikit-learn>=1.3.0",
        "statsmodels>=0.14.0",
        "matplotlib==3.8.3",
        "seaborn==0.13.2",
        "scipy>=1.12.0",
        "ipywidgets==8.1.2",
        "nbconvert==7.16.4",
        "streamlit>=1.32.0",
        "streamlit-option-menu>=0.3.0",
        "fastapi>=0.109.0",
        "uvicorn[standard]>=0.27.0",
        "python-multipart>=0.0.6",
    ],
    entry_points={
        "console_scripts": [
            "flsd-run=src.run_services:main",
            "flsd-api=src.api:start_api",
            "flsd-dashboard=src.dashboard:run_dashboard",
            "flsd-pipeline=src.pipeline:run_nightly_update",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Financial and Insurance Industry",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Office/Business :: Financial",
    ],
) 